/*
 * black stories v0.2
 * Issues: 4
 * Stories: 103
 */
var initialissue = 1;
var bss = new Array();
bss.push(new Object({issue:"1", name: "1", id:"01-001", title:"Mutters Beerdigung", hint:"<b>Bei der Beerdigung ihrer Mutter</b> sah sie einen Mann, den sie nicht kannte. Wenige Tage später tötete sie ihre Schwester.", solution:"<b>Während der Beerdigung</b> hatte sich die Frau unsterblich in den Mann verliebt. Dieser verschwand aber sofort nach der Beerdigung, ohne dass sie wusste, wie er hieß.<br/>Sie hoffte ihn auf der Beerdigung ihrer Schwester wieder zu sehen."}));
bss.push(new Object({issue:"1", name: "1", id:"01-002", title:"Besetzt", hint:"<b>Eine Frau starb,</b> weil sie zu lange telefonierte.", solution:"<b>Die Frau</b> hatte an ihrem Wagen neue Reifen montieren lassen. Die Mitteilung der Werkstatt, dass man bei der Montage vergessen hatte, die Reifenmuttern festzuziehen, konnte die Frau aber nicht erreichen, da sie mit ihrer Freundin \"dauertelefonierte\".<br/>In der ersten Kurve geriet ihr Fahrzeug außer Kontrolle und prallte gegen einen Baum."}));
bss.push(new Object({issue:"1", name: "1", id:"01-003", title:"Zwei Tote", hint:"<b>Zwei tote Männer</b> saßen an einem Tisch. In ihrer Mitte befand sich ein Schachspiel und ein Revolver.", solution:"<b>Die beiden Männer</b> befanden sich an Bord eines U-Bootes, das gekentert war. Die Luft reichte nur noch für einige Stunden.<br/>Da sie nur eine Patrone im Revolver hatten, spielten sie darum, wer sich erschießen durfte und wer ersticken musste."}));
bss.push(new Object({issue:"1", name: "1", id:"01-004", title:"Hinrichtung", hint:"<b>Auf dem Weg</b> zur Behörde wurde eine Frau umgebracht.", solution:"<b>Die Frau</b> hatte eine unglaubliche Erfindung gemacht und war auf dem Weg ins Patentamt. Sie hatte einen Motor erfunden, der mit bloßem Wasser fuhr – das \"Aus\" für die Mineralölindustrie.<br/>Die Ölmultis hatten ihr viel, ja sehr viel Geld dafür geboten, ihre Erfindung für immer in der Schublade verschwinden zu lassen. Doch die Frau wollte nicht. So griffen die Multis zu anderen Mitteln."}));
bss.push(new Object({issue:"1", name: "1", id:"01-005", title:"Verfluchter Urlaub", hint:"<b>Als der Mann</b> von der Toilette zurückkam, war der Urlaub im Eimer.", solution:"<b>Eine Frau</b> machte auf dem Weg in den Urlaub Halt an einer Raststätte. Sie glaubte, ihr Mann würde hinten im Wohnwagen schlafen.<br/>Dieser war jedoch aufgewacht und auf die Toilette gegangen. Als er zurückkam, war seine Frau nichts ahnend ohne ihn losgefahren."}));
bss.push(new Object({issue:"1", name: "1", id:"01-006", title:"Der Pilot", hint:"<b>Ein Pilot</b> schaute die Abendnachrichten und erhängte sich.", solution:"<b>Der (Militär-)Pilot</b> hatte bei einer Tiefflugübung das Seil einer vollbesetzten Gondel durchtrennt.<br/>Als er in den Abendnachrichten von dem Unglück hörte, würde ihm klar, was am Nachmittag dieses leichte Vibrieren am Leitwerk verursacht haben musste."}));
bss.push(new Object({issue:"1", name: "1", id:"01-007", title:"Der Mond", hint:"<b>Da der Mond</b> mit all seiner Kraft wirkte, erfuhr Heidi nicht, wer der Mörder war.", solution:"<b>Die Frau lag am Strand</b> und fing an, einen Krimi zu lesen.<br/>Sie war eingeschlafen, als die Flut das Buch für immer mitnahm."}));
bss.push(new Object({issue:"1", name: "1", id:"01-008", title:"Die Einarmigen", hint:"<b>Ein Mann</b> packte einen abgetrennten Arm in ein Paket und verschickte es. Das Paket kam bei drei einarmigen Männern an, welche den Inhalt zufrieden ins Meer warfen.", solution:"<b>Vor langer Zeit</b> trieben vier Männer gemeinsam in aussichtsloser Lage auf einem Baumstamm übers Meer. Ihr Schiff war gekentert. Da sie nichts zu essen hatten, vereinbarten sie, dass jeder einen Arm opfern müsse. Bevor der vierte an der Reihe war, wurden sie gerettet.<br/>Die drei erinnerten ihn an sein Versprechen und forderten einen seiner Arme. Da er in großer Entfernung zu ihnen lebte, dachte er nicht daran, sein Versprechen zu halten, gab eine Anzeige auf und bot demjenigen, der ihm seinen Arm abtreten würde, eine Million Euro. Schon bald fand sich ein Freiwilliger."}));
bss.push(new Object({issue:"1", name: "1", id:"01-009", title:"Rückwärts", hint:"<b>Als Jonas</b> einen Schritt rückwärts ging, starb er.", solution:"<b>Jonas arbeitete</b> als Fensterputzer im 40. Stock eines Hochhauses. Kurz vor Schichtende frisierte er sich im \"Spiegel\" der Hochhausfassade, da seine neue Freundin unten auf ihn wartete.<br/>Zum Schluss wollte er sich noch \"im Ganzen\" betrachten und machte einen (letzten) Schritt zurück."}));
bss.push(new Object({issue:"1", name: "1", id:"01-010", title:"Das Radio", hint:"<b>Ein Mann fuhr</b> mit seinem Wagen durch die Stadt. Er schaltete das Radio ein und erschoss sich.", solution:"<b>Sein Alibi</b> war geplatzt. Der Mann arbeitete als Moderator bei einem Radiosender. Er hatte einer komplette, mit seiner Moderation besprochene, CD eingelegt, um genügend Zeit zu haben, nach Hause zu fahren und seine Frau umzubringen.<br/>Gerade war er auf dem Rückweg zum Sender, als er das Radio einschaltete und feststellte, dass die CD \"hing\"."}));
bss.push(new Object({issue:"1", name: "1", id:"01-011", title:"Fünf Freunde", hint:"<b>Fünf Freunde</b> sprangen gemeinsam ins Meer. Nach einigen Stunden lebte keiner mehr.", solution:"<b>Bei sengender Hitze</b> verspürten die fünf Freunde unterwegs auf einem großen Segelboot im Mittelmeer das Bedürfnis, im kalten Nass ein wenig Erfrischung zu suchen.<br/>Auch der Kapitän und der Steuermann sprangen mit hinein. Niemand hatte daran gedacht, vorher die Bootsleiter herabzulassen."}));
bss.push(new Object({issue:"1", name: "1", id:"01-012", title:"Einfacher Mord", hint:"<b>Romeo und Julia</b> lagen tot am Boden, neben ihnen waren eine Pfütze und Glasscherben. Das Fenster war einen Spalt geöffnet, der Wind heulte.", solution:"<b>Romeo und Julia</b> waren zwei Fische, die sich noch vor kurzem in einem Aquarium auf der Fensterbank befanden.<br/>Eine Katze, die sich durch das offene Fenster zwängte, hatte das Aquarium zu Fall gebracht und damit den beiden jede Lebensgrundlage entzogen."}));
bss.push(new Object({issue:"1", name: "1", id:"01-013", title:"Der Nackte", hint:"<b>Am Fuß eines Berges</b> lag splitternackt ein toter Mann. In seiner Hand hielt er ein Streichholz.", solution:"<b>Ein Fesselballon</b> mit vier Mitfahrern an Bord war vom Kurs abgekommen und drohte am Berg zu zerschellen. Um Höhe zu machen, warfen die vier den gesamten Ballast (einschließlich ihrer Kleidung) über Bord.<br/>Es half nichts – einer musste springen. Sie losten. Der Tote hatte das kürzeste Streichholz gezogen."}));
bss.push(new Object({issue:"1", name: "1", id:"01-014", title:"Der Morgen", hint:"<b>Als die Frau</b> an einem wunderschönen Morgen aufwachte und einen kurzen Blick aus dem Fenster warf, nahm sie sich das Leben.", solution:"<b>Die Frau war das Oberhaupt</b> einer Sekte und hatte für diese Nacht den Weltuntergang prophezeit. Die meisten Anhänger der Sekte, einschließlich ihrer Kinder, hatten am Vorabend ein Gift eingenommen, um das Ende der Welt nicht erleben zu müssen.<br/>Die Frau selbst wollte sich dem schrecklichen Ereignis stellen und verzichtete auf das Gift. Als sie am Morgen feststellen musste, dass sie sich getäuscht hatte, nahm auch auch sie sich das Leben."}));
bss.push(new Object({issue:"1", name: "1", id:"01-015", title:"Danke", hint:"<b>Eine Frau ging in ein Lokal</b> und bestellte ein Glas Wasser. Der Mann hinter der Theke legte ein Gewehr an und zielte direkt auf sie. Die Frau bedankte sich und ging.", solution:"<b>Die Frau hatte Schluckauf</b> und wollte ihn mithilfe des Wassers loswerden.<br/>Der Mann hinter der Theke begriff sofort und wollte ihr helfen, indem er sie heftig erschreckte. Das war ihm geglückt!"}));
bss.push(new Object({issue:"1", name: "1", id:"01-016", title:"Verheißungsvolles Flackern", hint:"<b>Als das Licht flackerte,</b> wusste Stephan, dass er zu spät kam.", solution:"<b>Stephan war Anwalt</b> eines zu Tode Verurteilten. Letztendlich hatte er seine Begnadigung erwirkt, doch leider kam er zu spät.<br/>Das Licht flackerte, weil der \"elektrische Stuhl\" bereits aktiviert worden war."}));
bss.push(new Object({issue:"1", name: "1", id:"01-017", title:"Die weiße Taube", hint:"<b>Die Wahrsagerin prophezeite:</b> \"Eine weiße Taube wird sie töten.\" Wenig später war der Mann tot.", solution:"<b>Wenige Tage</b> nachdem der Mann die Wahrsagerin aufgesucht hatte, wurde er von einem Chirurgen namens Dr. Taube operiert.<br/>Die Operation missglückte und der Mann starb."}));
bss.push(new Object({issue:"1", name: "1", id:"01-018", title:"Die Sauna", hint:"<b>In der Sauna</b> lag neben einem toten Mann eine Thermosflasche.", solution:"<b>Der Mann</b> wurde mit einem Eiszapfen erstochen. Sein Mörder hatte den Eiszapfen in einer Thermosflasche mit in die Sauna gebracht.<br/>Der Eiszapfen war kurz darauf vollständig geschmolzen. Eine Tatwaffe wurde daher niemals gefunden."}));
bss.push(new Object({issue:"1", name: "1", id:"01-019", title:"Das Taxi", hint:"<b>Tino stieg in ein Taxi.</b> Als der Fahrer ihm am Bahnhof die Tür öffnete, fiel er tot aus dem Wagen.", solution:"<b>Ein Spinnenliebhaber</b> hatte seine hochgiftige Spinne im Taxi vergessen.<br/>Tino, der nächste Fahrgast, erblickte das Tier, geriet in Panik und wurde sogleich gebissen."}));
bss.push(new Object({issue:"1", name: "1", id:"01-020", title:"Todesprung", hint:"<b>Ein älterer Mann</b> im schwarzen Mantel und mit dunkler Brille fuhr mit dem Zug von A nach B. Zwei Wochen später fuhr er zurück und sprang in einem Tunnel aus dem Wagen.", solution:"<b>Jener ältere Herr</b> war nach B gefahren, um sich einer Augenoperation zu unterziehen. Er war blind. Auf der Rückreise nach A nahm er sich, während der Zug durch einen Tunnel fuhr, die Augenbinde ab.<br/>Völlig bestürzt darüber, dass er entgegen allen Versprechungen immer noch nichts sehen konnte, sprang er aus dem Zug."}));
bss.push(new Object({issue:"1", name: "1", id:"01-021", title:"Unbemerkt", hint:"<b>Obgleich alle gebannt den Mord beobachteten,</b> geschah er völlig unbemerkt.", solution:"<b>Eine Frau erstach ihren Mann</b> genau in dem Moment, als auf der Leinwand des Autokinos ebenfalls ein Mord begangen wurde."}));
bss.push(new Object({issue:"1", name: "1", id:"01-022", title:"Tödliche Stille", hint:"<b>Das Publikum lauschte</b> gespannt der Musik. Auf einmal war Stille. Und genau in diesem Moment kam jemand ums Leben.", solution:"<b>Ein Hochseilartist</b> und ein Musiker arbeiteten als Partner zusammen.<br/>Der Musiker sollte so lange spielen, bis der mit verbundenen Augen balancierende Hochseilartist am Seilende auf das Podest steigen konnte – nur diesmal lenkte den Musiker etwas im Publikum ab, und er hörte einen Moment zu früh auf."}));
bss.push(new Object({issue:"1", name: "1", id:"01-023", title:"Seltsam gekleidet", hint:"<b>Inmitten eines Waldes</b> befand sich eine seltsam gekleidete Leiche.", solution:"<b>Während einer großen Feuerlöschaktion</b> wurde ein Freizeittaucher aus Versehen von einem Löschflugzeug eingesaugt, als es im Tiefflug Wasser aufnahm.<br/>Über dem Waldbrandgebiet ließ das Löschflugzeug seine Wasserladung samt Taucher wieder ab."}));
bss.push(new Object({issue:"1", name: "1", id:"01-024", title:"Der Bürgermeister", hint:"<b>Ein Pfarrer</b> hielt eine Abschiedsrede. Kurz vor Ende erschien der Bürgermeister und wollte ihm danken. Er hatte noch nicht zu Ende gesprochen, als er erschossen wurde.", solution:"<b>Während seiner Rede</b> erwähnte der Pfarrer jenen seltsamen Mord, der sich am ersten Tag seiner Arbeit in der Gemeinde zugetragen hatte. Dabei erzählte er, dass die erste Beichte, die er abnahm die des Mörders war.<br/>Der Bürgermeister, der später dazustieß, berichtete seinerseits, dass er der Erste war, der den Beichtstuhl des Pfarrers aufgesucht hatte. Damit hatte er sich verraten und wurde noch während seiner Rede von einem Angehörigen des Mordopfers erschossen."}));
bss.push(new Object({issue:"1", name: "1", id:"01-025", title:"Erhängt", hint:"<b>In einem leeren Raum</b> hing ein Mann an einem Strick, unter ihm war eine Wasserlache.", solution:"<b>Aus Liebeskummer</b> (oder aus einem anderen Grund) war der Mann auf einen Eisblock gestiegen, welcher langsam unter seinen Füßen dahinschmolz."}));
bss.push(new Object({issue:"1", name: "1", id:"01-026", title:"Der Fahrzeugführer", hint:"<b>Ein Mann stieg</b> aus einem großen Fahrzeug und nahm sich das Leben.", solution:"<b>Der Mann war Landwirt</b> und fuhr seinen Mähdrescher in das Maisfeld, in dem seine Kinder unerlaubterweise Verstecken spielten.<br/>Als die Maschine stockte und er erkannte, dass er seine Kinder überfahren hatte, nahm er sich das Leben."}));
bss.push(new Object({issue:"1", name: "1", id:"01-027", title:"Billiger Porsche", hint:"<b>Für schlappe 500 Euro</b> verkaufte eine Frau den neuen Porsche ihres Ehemannes.", solution:"<b>Der Ehemann</b> hatte sich vor einem halbem Jahr das Leben genommen, indem er auf einem abgelegenen Waldstück die Abgase seines Porsches ins Innere leitete.<br/>Das Auto und die darin langsam verwesende Leiche wurden erst vier Monate später entdeckt. Der Leichengeruch ging nicht mehr aus dem Auto. Irgendwann hatte seine Frau und Erbin die Nase voll davon."}));
bss.push(new Object({issue:"1", name: "1", id:"01-028", title:"Das Spezialitäten-Restaurant", hint:"<b>Ein Mädchen</b> bestellte sich in einem Spezialitätenrestaurant ein Leguan-Steak. Nach dem ersten Bissen stand sie auf und warf sich vor einen vorbeifahrenden Lkw.", solution:"<b>Das Mädchen</b> hatte ein großes Schiffsunglück überlebt und war an eine Insel gespült worden. Schwer verletzt wurde sie von den anderen Überlebenden mit Wasser und Fleisch versorgt. Auf ihre Nachfragen, woher das ganze Fleisch komme, sagten ihr die anderen, dass sie zwei große Leguane erlegt hätten. Als die Schiffbrüchigen endlich gefunden wurden, war alle Qual vergessen.<br/>Bis zu dem Tag, an dem das Mädchen in besagtes Spezialitätenrestauant ging, um noch einmal (ihren \"Lebensretter\") Leguan zu essen. Nach dem ersten Bissen wurde ihr klar, dass es kein Leguanfleisch war, das sie gegessen hatte, sondern das Fleisch der an Land gespülten Leichen."}));
bss.push(new Object({issue:"1", name: "1", id:"01-029", title:"Ruinöser Schritt", hint:"<b>Eine Frau stand</b> vor einem Hotel. Nur noch zwei Schritte, und sie wäre völlig ruiniert.", solution:"<b>Die Frau</b> war Monopoly-Spielerin, deren Spielfigur nur noch zwei Schritte von der Schlossallee entfernt stand. Würde die Frau also in der nächsten Runde mit beiden Würfeln eine Eins würfeln, wäre sie bankrott."}));
bss.push(new Object({issue:"1", name: "1", id:"01-030", title:"Sportlich", hint:"<b>Nachdem er seine Frau mit dem Messer erstochen hatte,</b> fuhr er mit dem Fahrstuhl vom siebten Stock ins Erdgeschoss, bemerkte dort, dass er die Tatwaffe am Tatort vergessen hatte, fuhr in den dritten Stock und lief die restlichen vier Stockwerke bis zu seiner Wohnung hinauf.", solution:"<b>Der Mörder</b> war ein kleinwüchsiger Mann und konnte mit seiner Hand höchstens den Knopf des dritten Stockwerkes im Aufzug erreichen."}));
bss.push(new Object({issue:"1", name: "1", id:"01-031", title:"Das Paket", hint:"<b>Véronique</b> lag tot inmitten eines Roggenfeldes. Hinter ihr lag ein Paket. Weit und breit keine Spuren.", solution:"<b>Véronique,</b> eine leidenschaftliche Fallschirmspringerin, hatte Pech gehabt.<br/>Diesmal ließ sich ihr Schirm absolut nicht öffnen."}));
bss.push(new Object({issue:"1", name: "1", id:"01-032", title:"Das Hochhaus", hint:"<b>Eine vereinsamte Frau stürzte</b> sich vom Hochhaus. Kurz bevor sie aufschlug, bereute sie diesen Schritt.", solution:"<b>Die Frau war,</b> so glaubte sie, die einzige Überlebende eines Automkrieges. Nach über einem Jahr des Herumirrens entschloss sie sich, ihr Leben zu beenden.<br/>In dem Moment, in dem sie sich vom Hochhaus stürzte, hörte sie das Klingeln eines Telefons – irgendwo gab es also doch noch einen Menschen."}));
bss.push(new Object({issue:"1", name: "1", id:"01-033", title:"Tödliche Mahlzeit", hint:"<b>Eine Frau</b> gab einem Mann etwas zu essen. Einige Zeit später starben beide.", solution:"<b>Bei den beiden</b> handelte es sich um unsere aus der Bibel bekannten Ureltern Adam und Eva.<br/>Nachdem Adam den Apfel gegessen hatte, verloren die beiden ihre Unsterblichkeit."}));
bss.push(new Object({issue:"1", name: "1", id:"01-034", title:"Verschwundene Oma", hint:"<b>Eine Familie</b> wickelte die Oma vorsichtig in einen Teppich. Kurz darauf verschwand sie für immer.", solution:"<b>Als die Familie</b> im Ausland Urlaub machte, starb ihre Großmutter. Die Familie beschloss, um Formalitäten und Kosten zu vermeiden, die Oma in einem Teppich einzuwickeln und auf dem Dachgepäckträger über die Grenze nach Hause zu schaffen.<br/>Aber als sie unterwegs eine kurze Rast machten, entwendeten Diebe den Teppich – samt Großmutter."}));
bss.push(new Object({issue:"1", name: "1", id:"01-035", title:"Verschlafen", hint:"<b>Ein Mann schlief</b> in seinem Auto ein und ertrank.", solution:"<b>Der Fahrer eines Betonmischers</b> wurde von seiner Frau betrogen. Als er spät am Abend wieder einmal das Auto ihres Liebhabers vor seiner Haustür vorfand, lud er seine gesamte Ladung Beton durch das geöffnete Fenster in das Auto ab.<br/>Der Liebhaber saß aber bereits schon wieder in seinem Wagen und war eingeschlafen."}));
bss.push(new Object({issue:"1", name: "1", id:"01-036", title:"Neue Schuhe", hint:"<b>Marie ging in ein Geschäft</b> und kaufte sich neue Schuhe. Am Abend musste sie dafür sterben.", solution:"<b>Marie war die Frau</b> eines Messerwerfers. Ihre neuen Schuhe hatten höhere Absätze als die alten.<br/>Mit verbundenen Augen konnte ihr Mann, den sie überraschen wollte, den (Höhen-)Unterschied nicht sehen und warf die Messer in gewohnter Höhe."}));
bss.push(new Object({issue:"1", name: "1", id:"01-037", title:"Die offene Hose", hint:"<b>Ein Mann mit offener Hose</b> lag tot am Boden.", solution:"<b>Der Mann</b> musste mit dem Tode dafür bezahlen, dass er im Dunkel der Nacht von einer Eisenbahnbrücke auf eine Hochspannungsleitung hinuntergepinkelt hatte."}));
bss.push(new Object({issue:"1", name: "1", id:"01-038", title:"Revolverhelden", hint:"<b>Eine Frau ging</b> in ein leeres Lokal und bestellte an der Bar etwas zu trinken. Daraufhin erschoss der Mann hinter der Theke sie.", solution:"<b>Der Mann hinter der Theke</b> war gerade dabei, das Lokal auszurauben.<br/>Um nicht erkannt zu werden, musste er die einzige Zeugin töten, die ihm in die Quere kam."}));
bss.push(new Object({issue:"1", name: "1", id:"01-039", title:"Der Lichtschalter", hint:"<b>Der Bewohner</b> einer einsamen Behausung schaltete auf dem Weg ins Bett jeden Abend das Licht an. Als er eines Morgens Radio hörte, stürzte er sich ins Meer.", solution:"<b>Der Bewohner</b> der einsamen Behausung war Wärter des wichtigsten Leuchtturms an einer Küste. Im Radio wurde an diesem Morgen vom größten Schiffsunglück aller Zeiten berichtet.<br/>Am Abend zuvor hatte der Leuchtturmwärter tatsächlich vergessen, das Licht einzuschalten. Diesen Fehler würde er sich nie verzeihen."}));
bss.push(new Object({issue:"1", name: "1", id:"01-040", title:"Der Koffer", hint:"<b>Eine Frau öffnete</b> ihren Koffer. Als sie darin einen toten Mann fand, nahm sie sich das Leben.", solution:"<b>Der Tote</b> war ihr Freund. Da er keine Ausreiseerlaubnis aus seinem Heimatland bekam, hatte sie ihn in seinem Koffer versteckt und als Luftfracht aufgegeben.<br/>Leider war die Heizung im Frachtraum ausgefallen – und er erfror."}));
bss.push(new Object({issue:"1", name: "1", id:"01-041", title:"Löffel um Löffel", hint:"<b>Mit großer Freude</b> aß die Familie ihre Großmutter löffelweise auf.", solution:"<b>Nach dem Krieg</b> bekam die Familie von ihren Verwandten aus Amerika regelmäßig Pakete mit Nahrungsmitteln zugeschickt. Eines Tages war in dem Paket ein Behälter mit einem gräulichen Pulver. Die Familie dachte, es wäre ein Vitaminpräparat und jedes Familienmitglied schluckte davon einen Löffel pro Tag.<br/>Nach einigen Wochen trudelte ein Brief aus Amerika ein, in dem die Verwandten mitteilten, dass ihre Großmutter verstorben wäre, und dass man wunschgemäß die Asche in ihre deutsche Heimat überführt habe."}));
bss.push(new Object({issue:"1", name: "1", id:"01-042", title:"Kopflos", hint:"<b>Ein Mann</b> fuhr kopflos über die Straße.", solution:"<b>Der vor einem Motorrad fahrende Lastwagen</b> hatte einige Metallplatten geladen.<br/>Gerade als der Motorradfahrer zum Überholen ansetzte, löste sich eine Platte und trennte seinen Kopf sauber vom Rumpf."}));
bss.push(new Object({issue:"1", name: "1", id:"01-043", title:"Der schwarze Chevy", hint:"<b>Ein Mann erblickte</b> seinen schwarzen Chevy, tobte vor Wut und erwürgte den Meister.", solution:"<b>Der Mann</b> hatte seinen Chevy in die Lackiererei gebracht und wollte ihn feuerrot-metallic lackieren lassen. Nachdem ihm der Lackierer einen sehr hohen Preis dafür nannte, fragte der Mann: \"Und wenn Sie es schwarz machen?\"<br/>Der Lackierer meinte, das würde ca. 35 % billiger werden, woraufhin sie sich einigten. Doch der Lackierer meinte die Farbe und der Mann Steuerhinterziehung."}));
bss.push(new Object({issue:"1", name: "1", id:"01-044", title:"Der Spiegel", hint:"<b>Als Holger am Morgen</b> in den Spiegel schaute, machte er sein Testament.", solution:"<b>In der Disko</b> lernte Holger eine Frau kennen, mit der er noch in  derselben Nacht Sex hatte.<br/>Als er am Morgen aufwachte, war sie bereits verschwunden. Auf dem Spiegel im Badezimmer hatte sie \"Willkommen im Aids-Club\" hinterlassen."}));
bss.push(new Object({issue:"1", name: "1", id:"01-045", title:"Sägespäne", hint:"<b>Eine Frau</b> kam nach Hause und war überglücklich. Als sie auf dem Boden Sägespäne erblickte, fiel sie tot um.", solution:"<b>Die Frau litt</b> an Kleinwüchsigkeit. Als sie an diesem Tag nach Hause kam, glaubte sie endlich gewachsen zu sein. Denn erstmals konnte sie über den Tisch schauen.<br/>Als sie aber überall Sägespäne sah, wurde ihr klar, dass bloß ein übler Scherzbold ihr gesamtes Mobiliar \"verkürzt\" hatte. Das machte ihr schwaches Herz nicht mehr mit."}));
bss.push(new Object({issue:"1", name: "1", id:"01-046", title:"Gefährliches Telefonat", hint:"<b>In einer Telefonzelle</b> befand sich am Boden ein toter Mann. Überall war Blut, die Scheiben waren zerbrochen. Vor der Telefonzelle lag ein großer Fisch.", solution:"<b>Der Mann, ein Vollblut-Angler,</b> hatte seinen besten Freund angerufen, um ihm freudig mitzuteilen, wie groß der Fisch sei, den er gerade erst gefangen hatte.<br/>Seine maßlose Übertreibung unterstützte er mit heftiger Gestik. Dabei zerschlug er mit seinen begeistert herumrudernden Armen die Seitenscheiben der Telefonzelle, schnitt sich und verblutete."}));
bss.push(new Object({issue:"1", name: "1", id:"01-047", title:"Im Gebirge", hint:"<b>Im Gebirge</b> auf einer großen Lichtung lag ein toter Mann. Ein paar Meter entfernt lag ein Gewehr.", solution:"<b>Der Mann</b> war im Winter auf Hasenjagd. Beim Schuss auf das erste Tier löste sich eine Lawine, unter der er selbst begraben wurde.<br/>Erst im Frühjahr wurde der Leichnam gefunden."}));
bss.push(new Object({issue:"1", name: "1", id:"01-048", title:"Licht im Dunkeln", hint:"<b>Nachdem</b> ein Mann ein Streichholz angezündet hatte, starb er und musste nicht einmal begraben werden.", solution:"<b>Ein Strafgefangener</b> bestach den Leichenbestatter, ihm bei der Flucht zu helfen. Gegen Ende der nächsten Totenmesse im Gefängnis plante er, sich schnell zu dem Toten in den Sarg zu legen.<br/>In der Nacht sollte der Leichenbestatter das Grab öffnen und ihn befreien. Als der Gefangene im Sarg ein Streichholz anzündete, sah er den Leichenbestatter tot neben sich liegen."}));
bss.push(new Object({issue:"1", name: "1", id:"01-049", title:"Urlaub mit Folgen", hint:"<b>Der Urlaub</b> war seiner Gesundheit in keiner Weise zuträglich.", solution:"<b>Ein Mann</b> auf Argentinienrundreise rief sich ein Taxi und wurde vom Fahrer überwältigt. Als er spät in der Nacht weit außerhalb der Stadt aufwachte, hatte er eine frische Narbe am Rücken.<br/>Wieder zu Hause bestätigte sich sein übler Verdacht: Man hatte ihm die linke Niere gestohlen."}));
bss.push(new Object({issue:"1", name: "1", id:"01-050", title:"Mord ohne Folgen", hint:"<b>Eine Frau</b> erschoss ihren Ehemann. Die Polizei führte sie ab, ließ sie aber bald darauf wieder frei.", solution:"<b>Die Frau</b> hatte für den Mord an ihrem Ex-Ehemann bereits jahrelang hinter Gittern gesessen. Ein Justizirrtum, denn der Ex-Mann hatte sich in Wirklichkeit aus dem Staub gemacht.<br/>Da die Frau bereits für die Ermordung eines Ehemannes bestraft worden war, sah die Polizei keine Veranlassung, sie länger festzuhalten."}));

bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-001", title:"Stiller Abend", hint:"<b>Ein junges Mädchen sitzt</b> abends allein in einem fremden Auto an einem einsamen Waldrand. Als es ein scharrendes Geräusch hört, fällt es in Ohnmacht.", solution:"<b>Das Mädchen</b> und sein Freund knutschen im Auto. Im Autoradio hören sie, dass in der Nähe ein geisteskranker Killer aus der Irrenanstalt ausgebrochen ist. Auf einmal lässt das Auto sich nicht mehr starten und der Freund will Hilfe holen. Als das Mädchen das Geräusch hört, ahnt sie, dass der Killen ihren Freund überfallen und über dem Auto aufgehängt hat. Die Füße ihres sterbenden Freundes scharren auf dem Wagendach.</p><p class='em'>Im Horrofilm \"Ich weiß, was du letzten Sommer getan hast\" (USA 1997 \"I Know What You Did Last Summer\") erzählt sich die Teenager-Clique einer High School solche Schauermärchen am Lagerfeuer. Noch glauben die Schüler, dass es sich lediglich um alberne Gruselgeschichten für Pfadfinder handle. Doch bald wird daraus blutige Realität.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-002", title:"Kampflos", hint:"<b>Der Versicherungsvertreter lümmelt</b> an der Bar herum. Der Mars steht zu oft im Todeshaus, meint er, deshalb gehen seine Geschäfte schlecht.", solution:"<b>Der Vertreter verkauft</b> Lebensversicherungen. Aber bevor er eine abschließt, schaut er zuerst in die Sterne und analysiert die astrologische Situation seines Klienten. Und weil die Sterne momentan häufig schlecht stehen, will er keine Verträge abschließen. Es wäre doch zu blöd, jemanden zu versichern, der kurz darauf stirbt.</p><p class='em'>Dieser Meinung ist Hieronymous B. Mistelzweig im Krimi \"Die 1000 Augen des Dr. Mabuse\" (Deutschland/Frankreich/Italien 1960). Der erste Mabuse-Film entstand 1922 durch Fritz Lang. Der hier genannte Schwarz/weiß-Film ist der Auftakt einer Mabuse-Reihe in den sechziger Jahren. Der Film spielt in dem noch von Nazis erbauten Hotel Luxor, welches von einer geheimen Zentrale dank Fernsehkameras überall ausspioniert werden kann.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-003", title:"Mord in der Villa", hint:"<b>Obwohl sich der Tatort</b> im ersten Stock befindet, weiß der Kommissar schon im Wohnzimmer, dass ein Mord geschehen ist.", solution:"<b>Der Kommissar</b> braucht nur an die Wohnzimmerdecke zu schauen. Von dort tropft das Blut des Opfers herab.</p><p class='em'>Diese grausige Szene stammt aus dem Horrofilm \"Nightmare – Mörderische Träume\" (USA 1984 \"A Nightmare on Elm Street\"). Vier Teenager werden von Albträumen geplagt, die sich als tödlich erweisen. Denn hinter den Albträumen steckt Freddy Krueger, der Mann mit der verbrannten Visage und vier Messern an der Hand. Der Regisseur und Drehbuchautor Wes Craven wählte diesen Namen, weil er im Kindesalter von einem Jungen namens Freddy Krueger geplagt worden war.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-004", title:"Zornig?", hint:"<b>Die Frau sagt</b> zu ihrem Ehemann: \"Es tut mir leid, dass ich dich nicht früher abgeholt habe. Bist du mir jetzt böse?\" Doch er antwortet nicht.", solution:"<b>Der Leichenbestatter</b> hat die Frau mehrmals gebeten, die Urne mit der Asche ihres Mannes abzuholen. Aber die Frau war so in ihrer Trauer versunken, dass sie es nicht konnte. Endlich tut sie es und bittet ihren verstorbenen Ehemann um Verzeihung.</p><p class='em'>Eine Filmszene aus der schwarzen Komödie \"Dead by Monday\" (Schweiz/Deutschland 2001). Beim Freeclimbing verunglückt der Ehemann von Julie und lässt sie allein zurück. Als Julie zufällig entdeckt, dass ihr Mann sie zu Lebzeiten mit einer anderen Frau betrogen hat, möchte sie sich in ihrer Verzweiflung das Leben nehmen. Nur: so einfach geht das nicht. Trotz des düsteren Themas werden die Lachmuskeln bei diesem Film arg strapaziert.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-005", title:"Shakehands", hint:"<b>Tatort:</b> Die Küche einer Gaststätte. Der unbewaffnete Junkie wird von einem schwerbewaffneten Schurken verfolgt. Der Junkie ergreift ein Küchenmesser, mit dem es ihm gelingt, den Schurken zu verletzen. Dann nimmt der Junkie die Hand des Schurken. Das überlebt der Schurke nicht.", solution:"<b>Mit dem Hackmesser</b> hat der Junkie dem Schurken die Hand abgeschlagen. Als der Schurke wütend vor Zorn und Schmerz zum Angriff ansetzt, hebt der Junkie die Hand des Schurken vom Küchenboden auf, die den Revolver noch fest umklammert hält. Und so kann der Junkie den Schurken erschießen.</p><p class='em'>Auf diese Weise kommt im Actionfilm \"Crank\" (Großbritannien/USA 2006) der Bruder des Oberschurken Ricky Verona ums Leben. Chev, der Held des Films, ist Profikiller. Ricky hat ihm einen \"Beijing-Cocktail\" ins Blut gespritzt, der den Adrenalinfluss hemmt und Chev innerhalb einer Stunde töten wird. Chev hat nur eine Möglichkeit: er muss ständig in Bewegung bleiben. So rast er im Höllentempo durch Los Angeles, rettet seine Freundin und vernichtet die Schurken, bevor er stirbt. Die Schauplätze werden mit Google Earth herangezoomt.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-006", title:"Hals- und Beinbruch", hint:"<b>Kurz vor seinem schweren Unfall</b> murmelt das Opfer: \"Die Sonne scheint von unten.\"", solution:"<b>Es ist Krieg.</b> Das Opfer ist Pilot und sitzt am Steuer eines Jagdflugzeugs. Wegen einer Schusswunde kämpft der Pilot gegen die Bewusstlosigkeit an und hat die Maschine nicht mehr unter Kontrolle. Das Flugzeug dreht sich und fliegt mit der Bauchseite nach oben. So hat der Pilot den Eindruck, dass die Sonne von unten scheine. Danach stürzt der Pilot ab.</p><p class='em'>Diese Szene stammt aus Charlie Chaplins Satire \"Der große Diktator\" (USA 1940 \"The Great Dictator\"). Charlie Chaplin, der zusammen mit dem halbtoten Piloten Schultz in einem offenen Flugzeug sitzt, merkt nicht, dass es sich gedreht hat. Chaplin wundert sich, dass plötzlich die Gesetze der Schwerkraft verrückt spielen. So fließt beim Öffnen der Wasserflasche das Wasser unerwartet \"nach oben\".</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-007", title:"Der Lippenstift", hint:"<b>Damit seine Freundin nicht verletzt</b> wird, leert der Mann ihre Handtasche aus.", solution:"<b>Der Mann</b> hat gerade einen Killer entdeckt. Es bleibt keine Zeit, die Freundin in Sicherheit zu bringen. Deshalb schüttet er den Inhalt ihrer Handtasche auf den Boden. Die Freundin bückt sich instinktiv und räumt die Tasche wieder ein, während über ihr die Kugeln pfeifen.</p><p class='em'>Als schwarze Komödie mit Actionelementen kann man den Film \"Crank\" (Großbritannien/USA 2006) bezeichnen. Bei der Schießerei bleibt die Freundin am Leben, von einem Wellensittich bleiben allerdings nur noch die Federn übrig. Sämtliche Stunts wurden von den Darstellern selbst ausgeführt – auch der Helikopter-Zweikampf und der Sturz vom Hochhaus. Denn die Regie war der Meinung, dass es langweilig wäre, die Hinterköpfe von Doubles aufzunehmen.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-008", title:"Der Jammerlappen", hint:"<b>Die Frau schreit verzweifelt</b> um Hilfe. Doch obwohl der Mann nur einen Schritt vor der Frau steht, tut er rein gar nichts.", solution:"<b>Die Frau ist beim Blumenpflücken</b> an der Kante einer Steilküste abgerutscht und kann sich nur noch mit den Händen festhalten. Unter ihr befindet sich ein tiefer Abgrund. Der Mann, der zufällig vorbeikommt, kann die Frau weder hören noch sehen, denn er sieht ihre Hände im Gebüsch nicht und auf seinen Ohren trägt er Kopfhörer. Im Dröhnen der Musik gehen die Schreie der Frau unter.</p><p class='em'>Wenig später lernen sich Julie und Alex im Film \"Dead by Monday\" (Schweiz/Deutschland 2001) doch noch kennen. Und bald haben die beiden jungen Leute ein reizvolles Hobby: sie wollen gemeinsam einen hübschen Freitod erleben. Das führt die beiden schließlich bis zu den Niagara-Fällen. Dort müsste es wundervoll sein, in den Fluten zu ertrinken, meint Julie begeistert.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-009", title:"Tod beim Camping", hint:"<b>Eine Frau rennt</b> mit ihrem Baby aus dem Zelt, wirft sich in einen Wasserfall und ertrinkt mit einem milden Lächeln.", solution:"<b>Ein Raubtier</b> hat sich in das Zelt geschlichen. Als einzige Rettung sieht die Frau die Möglichkeit, sich mit dem Baby in die reißenden Fluten zu stürzen. Mit letzter Kraft kann die Frau flussabwärts das Baby ans rettende Ufer schieben, während sie selbst ertrinkt – mit einem milden Lächeln, weil sie ihr Baby in Sicherheit weiß.</p><p class='em'>Im Trickfilm \"Ice Age\" (USA 2002) kommen auf diese Weise das behäbige Mammut Manfred und das nervtötende hyperaktive Faultier Sid unerwartet zu einem Menschenbaby. Sie retten es vor den gefräßigen Säbelzahntigern und nach vielen Abenteuern bringen sie das Baby zurück zu den Steinzeit-Menschen. Als Running Gag ist immer wieder das Säbelzahn-Eichhörnchen Scrat (aus Squirrel + Rat) zu sehen, welches vergeblich versucht, eine Eichel zu vergraben.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-010", title:"Der Schädling", hint:"<b>Der Verfolger hat</b> ein gutes Versteck vor den schießwütigen Schurken gefunden. Doch weil er husten muss, verlässt er das Versteck und begibt sich in tödliche Gefahr.", solution:"<b>Der Verfolgte</b> hat sich in einem Maisfeld versteckt. Die Schurken verfolgen ihn in einem Flugzeug, welches eigentlich für das Versprühen von Insektenpulver eingesetzt werden sollte. Sie nebeln das Maisfeld ein und treiben so den Verfolgten aus seinem Versteck.</p><p class='em'>Die berühmte Maisfeld-Szene hat Filmgeschichte geschrieben und stammt aus dem Thriller \"Der unsichtbare Dritte\" (USA 1959 \"North by Northwest\"), einem Meisterwerk von Alfred Hitchcock. Im Film hat der Verfolgte mächtig Glück, dass in dem Moment, als er das Maisfeld verlässt, ein Tanklastwagen angedonnert kommt und die Schurken in ihrem Doppeldecker-Flugzeug nicht mehr ausweichen können.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-011", title:"Die Zombiekiller", hint:"<b>Die Stadt wimmelt</b> von schlurfenden beißwütigen Zombies. Dennoch gelingt es den noch lebenden Freunden, heil durch die Zombiehorde zu gelangen und zu entkommen.", solution:"<b>Die Freunde tun so,</b> als seien sie selbst auch Zombies. Mit lahmem Watschelschritt, schlackernden Armen und betrunkenem Blick fallen sie unter den Zombies nicht auf. Deshalb werden sie von den Zombies in Ruhe gelassen.</p><p class='em'>In der Horrorparodie \"Shaun of the Dead\" (Großbritannien 2004) wehren sich Shaun und seine Freunde kreativ gegen eine Übermacht von Zombies. Uralt-Schallplatten eignen sich etwa prima als Wurfgeschosse. Shauns Mitbewohner Ed wird zwar gegen Ende des Films selbst ein Zombie, das macht aber nichts. Shaun legt ihn im Gartenschuppen an die Kette und dann können die beiden wieder gemeinsam stundenlang Computerspiele spielen.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-012", title:"Das Geschenk", hint:"<b>Der Mörder soll</b> ins Gefängnis eingeliefert werden. Vorher aber überreicht er dem Kommissar ein Paket. Danach wird der Mörder nicht mehr eingeliefert.", solution:"<b>Der Mörder</b> hat die Frau des Kommissars getötet. In dem Paket ist ihr Kopf. Der Kommissar erschießt den Mörder sofort.</p><p class='em'>So endet der bluttriefende Thriller \"Seven\" (USA 1995 \"Se7en\"). Der Heißsporn Davis Mills (Brad Pitt) ermittelt als junger aufstrebender Kommissar in einem Fall von besonders brutalem Serienmord. Bei den Dreharbeiten brach sich Brad Pitt bei der Mörderjagd einen Arm, was geschickt ins Drehbuch integriert wurde.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-013", title:"Muttermal", hint:"<b>Ein reicher Dandy wacht aus</b> einem unruhigen Schlaf auf. Neben ihm liegt eine Frau. Ihr Gesicht ist noch unter dem Bettlaken verborgen. Als der Mann auf ihrem nackten Körper einen Leberfleck entdeckt, weiß er, dass er einen Riesenfehler gemacht hat.", solution:"<b>Der reiche Dandy kennt</b> zwei Frauen: seine wahre Liebe und eine eifersüchtige attraktive Blondine. Als der Mann die Bösartigkeit der Blondine realisiert, wird er in seinem Rausch so wütend, dass er sie mit dem Kissen erstickt. Doch am nächsten Morgen erkennt er an dem Leberfleck, dass er in Wirklichkeit eine wahre Liebe ermordet hat.</p><p class='em'>David Aames, der selbstsüchtige Held im Filmdrama \"Vanilla Sky\" (USA 2001) erwürgt in Panik das blonde Model Julie Gianni (Cameron Diaz). Doch dann bemerkt er mit Schrecken, dass er stattdessen seine Traumfrau Sofia Serrano getötet hat. Ist es Wahrheit oder Traum? Und zielen die dunklen Machenschaften nur darauf ab, David vom Thron seiner Firma stürzen zu wollen? Der Film lässt bewusst viele Interpretationen zu.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-014", title:"Schmerzhafte Trauer", hint:"<b>Die Trauerrede wird gehalten,</b> der Sarg wird in das Erdloch gelegt und danach werden die Kinder verhauen.", solution:"<b>Die Kinder</b> haben \"Begräbnis\" gespielt. Das wäre eigentlich nicht schlimm, hätten die Kinder dabei nicht die Katze in einer Pappschachtel lebendig vergraben.</p><p class='em'>Angeregt durch eine Filmszene aus \"Die Addams Family in verrückter Tradition\" (USA 1993 \"Addams Family Values\"). Düster und morbid ging es schon zu, als diese Kult-Familie in den 60er-Jahren nur in schwarz-weiß zu sehen war. Die finstere Gesinnung ist in Farbe genauso schwarz. Im Film werden die Kinder natürlich nicht verprügelt, denn Mutter und Vater Addams lieben das Makabere.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-015", title:"Todeskuss", hint:"<b>Der Geheimagent soll meuchlings</b> ermordet werden. Aber ein Kuss rettet ihm das Leben.", solution:"<b>Die niederträchtige Frau</b> soll den Geheimagenten mit einem Kuss ablenken, während sich der Mörder von hinten anschleicht. Doch in der Pupille der Frau spiegelt sich der Mörder. Blitzschnell wirbelt der Geheimagent die Frau herum, während der Mörder bereits zuschlägt.</p><p class='em'>Eine Szene im Vorspann des Films \"Goldfinger\" (Großbritannien/USA 1964). Dieser James-Bond-007-Film, in dem die Goldreserven von Fort Knox versucht werden soll, gilt als der beste Bond-Film überhaupt. Der Film enthält Hinweise auf die Sage von König Midas, bei der sich alles, was Midas berührte, in Gold verwandelte.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-016", title:"Erschieß mich!", hint:"<b>Der Soldat gibt</b> dem General eine Pistole und bittet den General, auf ihn zu schießen. Dieser feuert und der Soldat fällt sofort tot um.", solution:"<b>Der Soldat will</b> dem General die neu entwickelte, todsichere Schussweste vorführen. Leider ist die Weste in Wirklichkeit alles andere als schusssicher. Das hatte der Soldat so nicht erwartet.</p><p class='em'>Aus dem Film \"Der große Diktator\" (USA 1940 \"The Great Dictator\") von Charlie Chaplin. Der Film wurde zur Zeit des Zweiten Weltkriegs hergestellt und ist Chaplins Abrechnung mit Hitler. Der Diktator im Film Anton Hinkel und spricht wie Hitler (\"Demokratie schtonk! – die Demokratie wird abgeschafft!\"). Jeder Filmbegeisterte erinnert sich an die Szene, in der Hinkel im Größenwahn mit der Erdkugel spielt und der Ballon plötzlich zwischen den Händen des Weltherrschers zerplatzt.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-017", title:"Spurlos", hint:"<b>Der Mörder zieht</b> bei seinen Morden keine Handschuhe an. Und doch sind später am Tatort keine Fingerabdrücke zu finden.", solution:"<b>Der Mörder</b> hat vor der Tat seine Fingerspitzen mit Klebstoff beschmiert.</p><p class='em'>Diesen Trick wendete der \"Zodiak-Killer\" (USA 2005 \"The Zodiac\") bei seinen Morden an. Der Filmthriller hält sich eng an die wahren Begebenheiten. Über ein Jahrzehnt lang beschäftigte der Zodiac-Killer die amerikanische Polizei. Der Killer bekannte sich selbst zu 37 Morden. Er glaubte, dass die ermordeten Personen ihm im Paradies als Sklaven dienen müssen. Der Zodiac-Killer wurde nie gefasst. Seine letzte Nachricht stammt aus dem Jahr 1978.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-018", title:"Nacktes Grauen", hint:"<b>Während der Vorhang</b> zerreißt, erleidet die hübsche Blondine einen grauenhaften Tod.", solution:"<b>Die Blondine</b> steht nackt in der Dusche, als ein Meuchelmörder ihr das Messer in den Bauch rammt. Die halbtote Frau versucht, sich noch am Duschvorhang festzuhalten. Doch die Ringe reißen aus dem Stoff und die Frau fällt zu Boden.</p><p class='em'>Dies ist die prominente Duschszene aus Hitchcocks Filmthriller \"Psycho\" (USA 1960). Die junge Sekretärin Marion hat gerade 40 000 Dollar unterschlagen. Auf der Flucht hält sie bei einem heruntergekommenen Motel an und wird von dem geisteskranken Inhaber Norman gemeuchelt. Obwohl in schwarz-weiß gedreht, sieht man förmlich das Blut in den Abfluss der Dusche rinnen.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-019", title:"Scharfe Sache!", hint:"<b>Der Gast rasiert</b> sich mit einem scharfen Rasiermesser. Und da passiert es: er ritzt sich den Hals. Der Gastgeber, der dem Gast zugeschaut hat, ist außer sich vor Freude.", solution:"<b>Der Gastgeber</b> ist ein Vampir, der sich von Blut ernährt. Rasch lässt er sich vom Gast das blutige Rasiermesser geben und leckt es mit der Zunge ab. Welche himmlische Delikatesse!</p><p class='em'>In \"Bram Stoker's Dracula\" (USA 1992 \"Dracula\") wird der junge Londoner Anwalt Jonathan Harker wegen eines Immobilienverkaufs ins finstere Transsylvanien geschickt. Dort, im düsteren Schloss des Grafen Dracula, wird Jonathan unversehens vom Gastgeber zum Gefangenen. Denn Jonathan besitzt einen kostbaren Schatz: sein eigenes Blut! Der mit prominenten Stars besetzte oscargekrönte Film schwelgt in albtraumhaften Bildern.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-020", title:"Ein guter Riecher", hint:"<b>Das verliebte Paar flüchtet</b> vor den Verfolgern. Mit viel Glück wird es schließlich durch eine Nase gerettet.", solution:"<b>Die Verfolgungsjagd</b> findet in Amerika statt. Das Paar flüchtet, indem es versucht, sich in den steilen Felsen des Mount Rushmore in Süd-Dakota zu verstecken. Im Abhang des Mount Rushmore sind dort riesenhaft vergrößert die Gesichter amerikanischer Präsidenten nachgebildet. Als das Paar abrutscht, ist es eine steinerne Präsidentennase, die ihm Halt gibt, während die Verfolger in die Tiefe stürzen.</p><p class='em'>Angeregt durch eine Szene aus dem Spionagethriller \"Der unsichtbare Dritte\" (USA 1959 \"North by Northwest\"). Gegen Ende des Films gibt es am Mount Rushmore National Memorial, mitten zwischen den steinernen Präsidentengesichtern, einen Showdown. Kaum zu glauben, dass dieser Hitchcock-Klassiker schon 50 Jahre alt ist. Der spannendheitere Streifen beeinflusste später die James-Bond-Filme.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-021", title:"Mach mal Pause!", hint:"<b>Die Welt steht</b> nahe vor dem Untergang. Nur ein Kommandant auf einem einsamen, umkämpften Stützpunkt kann sie noch retten. Und deshalb schießt er mit seiner Waffe auf einen Cola-Automaten.", solution:"<b>Nur dieser Kommandant</b> kennt den Code, mit dem man die finale Atomexplosion noch stoppen kann. Und diesen Code muss er dem Präsidenten der USA übermitteln. Doch das einzige noch funktionsfähige Telefon ist ein Münzapparat. Weil der Kommandant nicht genügend Münzen in der Tasche hat, besorgt er sich welche auf unsanfte Art aus einem Cola-Automaten.</p><p class='em'>Die Schießerei auf den Cola-Automaten löst im Film \"Dr. Seltsam oder: Wie ich lernte, die Bombe zu lieben\" (Großbritannien 1964 \"Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb\") eine Münzenlawine aus. Damit kann zwar die Telefonverbindung zum Präsidenten hergestellt werden, der Weltuntergang findet allerdings dennoch statt. Die bitterböse Atomkriegs-Satire über das paranoide \"Gleichgewicht des Schreckens\" während des kalten Krieges stammt von Kult-Regisseur Stanley Kubrick.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-022", title:"Unruhestand", hint:"<b>Der Mordkommissar soll</b> in einer Woche pensioniert werden. Als sein Assistent einen Toten untersucht, entdeckt er im Büro des Opfers das mit Blut geschriebene Wort \"Habgier\". Da ahnt der Kommissar, dass er in seiner letzten Arbeitswoche noch viel zu tun haben wird.", solution:"<b>\"Habgier\"</b> ist eine der sieben Todsünden (neben Völlerei, Trägheit, Wollust, Hochmut, Neid und Zorn). Der Kommissar vermutet, dass der Täter deshalb noch weitere Morde verüben wird.</p><p class='em'>Der Thriller \"Seven\" (USA 1995 \"Se7en\") ist auf den sieben Todsünden aufgebaut. Der Mörder versucht an sieben Tagen durch sieben schreckliche Morde die Welt aufzurütteln und ihr sündhaftes Verhalten anzuprangern. Die letzten beiden Morde sind dabei besonders raffiniert angelegt. Denn am Ende gewinnt der Mörder, auch wenn er getötet wird.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-023", title:"Verwundet", hint:"<b>Der Verkäufer</b> in einem Elektrowarengeschäft trägt eine Krawatte und ein weißes Hemd. Plötzlich färbt sich das Hemd blutrot. Doch den Verkäufer scheint das nicht sonderlich zu stören. Er macht weiter mit dem Verkaufsgespräch.", solution:"<b>Der Verkäufer</b> trägt in der Hemdtasche einen Kugelschreiber. Die rote Tinte ist ausgelaufen.</p><p class='em'>\"Shaun of the Dead\" (Großbritannien 2004) beginnt für Shaun dem Versager alltäglich. Die Wohngemeinschaft vermüllt, Shauns Freundin setzt ihn vor die Tür und Shauns Stiefvater nervt. Doch als London von Zombies heimgesucht wird, läuft Shaun zu Hochform auf. Er erklärt seine Stammkneipe zur Festung. In der Horrorparodie sind viele Anspielungen zu finden, beispielsweise auf den Zombiefilm \"Dawn of the Dead\".</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-024", title:"Bowling", hint:"<b>Der Polizist bedroht</b> den Bösewicht mit einer Pistole. Als der Kopf rollt, ist der Bösewicht zu einem Geständnis bereit. Dabei kommt niemand ums Leben.", solution:"<b>Im Haus</b> des arglistigen Geschäftsmannes wimmelt es von Kunstschätzen: kostbare Ming-Vasen, echte Gemälde, wertvolle Statuen. Der Polizist schießt auf eine Statue, deren Kopf herabfällt. Da ist der Mann bereit, auszusagen, um nicht noch mehr seiner geliebten Antiquitäten zu verlieren.</p><p class='em'>Der Thriller \"The Black Dahlia\" (Deutschland/USA 2006) besitzt Anklänge eines Film Noir. Viel Wert wurde auf eine reiche Ausstattung gelegt, dabei unterliefen den Machern allerdings etliche Fehler. Der Film spielt 1947 in Los Angeles, doch zu jener Zeit gab es viele Dinge noch nicht, die der Film zeigt, zum Beispiel die Stoppschilder, die in den USA erst in den fünfzigern Jahren eingeführt wurden.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-025", title:"Der Raub", hint:"<b>Während eine Frau</b> durch ein Fernrohr schaut und in ein Mikrofon spricht, bringt sie einen Mann zur Verzweiflung und raubt ihm das letzte Hemd.", solution:"<b>Zwei Männer spielen</b> Karten um viel Geld. Einer der Männer trägt einen als Hörgerät getarnten Empfänger im Ohr. Die Frau schaut das Fernrohr auf die Kartenhand des Gegners und übermittelt dem Mann per Funk, welche Karte der Gegner gerade gezogen hat.</p><p class='em'>Jill Masterson, die Assistentin des Goldschmugglers \"Goldfinger\" (Großbritannien/USA 1964) trägt auf diese Weise im gleichnamigen James-Bond-007-Film dazu bei, dass ihr Meister tausende von Dollars gewinnt. Doch unverhofft kommt James Bond dazu, stellt den Funk ab und vergnügt sich mit Jill. Das bekommt ihr schlecht, denn sie liegt bald tot und ganz mit Gold überzogen im Bett.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-026", title:"Gib mir Saures!", hint:"<b>Es ist Halloween.</b> Der übermütige Kerl trägt eine Maske und die Leute erschrecken furchtbar. Doch am nächsten Tag setzt er die Maske nicht ab. Und auch nicht am übernächsten Tag.", solution:"<b>Der Mann</b> hatte einen Unfall. Sein Gesicht wurde frisch operiert. Damit das Gewebe besser heilt, muss er andauernd eine Latexmaske tragen.</p><p class='em'>Der steinreiche David hat im Film \"Vanilla Sky\" (USA 2001) nach einem Autounfall ein entstelltes Gesicht. Die Ärzte verpassen ihm eine Maske. Doch David fragt sich, was er an den 364 Tagen außer Halloween damit machen soll. Der Titel \"Vanilla Sky\" bezieht sich auf ein Gemälde von Claude Monet. Der Film ist ein Remake des spanischen Originals \"Abre los ojos\" (Öffne die Augen). Und das ist auch Davids Lebensziel.</p>"}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-027", title:"Stürmische Nacht", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-028", title:"Ätsch!", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-029", title:"Tödliche Sucht", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-030", title:"Schwein gehabt", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-031", title:"Gefüllte Torte", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-032", title:"Gute Aussicht", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-033", title:"Der Lebensretter", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-034", title:"Feurige Liebe", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-035", title:"Einbrecherwerkzeug", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-036", title:"Teure Fahrt", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-037", title:"Das war's dann!", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-038", title:"Panik", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-039", title:"Geh auf!", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-040", title:"Einkaufszettel", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-041", title:"Gefährliche Arbeit", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-042", title:"Waldesruhe", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-043", title:"Pfusch am Bau", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-044", title:"Grausamer Gebieter", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-045", title:"Krönung", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-046", title:"Die Untote", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-047", title:"Der Kannibale", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-048", title:"Die Krankheit", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-049", title:"Wagenwechsel", hint:"<b></b> ", solution:"<b></b> "}));
bss.push(new Object({issue:"movie", name: "Movie Edition", id:"movie-050", title:"Todesangst", hint:"<b></b> ", solution:"<b></b> "}));

bss.push(new Object({issue:"shit-happens", name: "Shit Happens Edition", id:"shit-happens-001", title:"?", hint:"<b>?</b> ?", solution:"<b>?</b> ?"}));

bss.push(new Object({issue:"custom", name: "Custom", id:"custom-001", title:"Adam & Eva", hint:"<b>Als Wissenschaftler</b> zwei eingefrorene Menschen in einem Eisberg entdecken, wussten sie sofort, dass sie Adam und Eva hießen.", solution:"<b>Die beiden nackten Körper</b> waren sehr gut in dem durchsichtigen Eis erhalten geblieben. So konnten die Wissenschaftler sofort erkennen, dass beide keinen Bauchnabel hatten. Somit musste es sich um die allerersten Menschen Adam und Eva handeln."}));
bss.push(new Object({issue:"custom", name: "Custom", id:"custom-002", title:"Die Socke", hint:"<b>Ein Mann</b> fand eine Socke am Rande eines Feldweges. Kurz darauf lauschte er aufmerksam und freute sich.", solution:"<b>Der Mann</b> hatte zuvor sein Handy, welches er in einer Babysocke aufbewahrt hatte, verloren. Ein unbekannter Finder nahm das Handy aus der Socke und versteckte es im nahegelegenen Feld. Wohl wissend, dass nur der Besitzer seine Handy-Socke wiedererkennen würde, ließ er die unscheinbare Socke auf dem Weg zurück. Als der Besitzer später die Socke wiederfand, rief er mit einem anderen Handy sein Eigenes an. Nun brauchte er nur noch dem Klingelton zu dem versteckten Handy zu folgen."}));

bss.push(new Object({issue:"2", name: "2", id:"02-001", title:"02-001:Erhängt", hint:"In einem leeren Raum hing ein Mann an einem Strick, unter ihm war eine Wasserlache.", solution:""}));
bss.push(new Object({issue:"2", name: "2", id:"02-002", title:"02-002:Erhängt", hint:"In einem leeren Raum hing ein Mann an einem Strick, unter ihm war eine Wasserlache.", solution:""}));
bss.push(new Object({issue:"2", name: "2", id:"02-003", title:"02-003:Erhängt", hint:"In einem leeren Raum hing ein Mann an einem Strick, unter ihm war eine Wasserlache.", solution:""}));

bss.push(new Object({issue:"3", name: "3", id:"03-001", title:"03-001:Erhängt", hint:"In einem leeren Raum hing ein Mann an einem Strick, unter ihm war eine Wasserlache.", solution:""}));
bss.push(new Object({issue:"3", name: "3", id:"03-002", title:"03-002:Erhängt", hint:"In einem leeren Raum hing ein Mann an einem Strick, unter ihm war eine Wasserlache.", solution:""}));
bss.push(new Object({issue:"3", name: "3", id:"03-003", title:"03-003:Erhängt", hint:"In einem leeren Raum hing ein Mann an einem Strick, unter ihm war eine Wasserlache.", solution:""}));

bss.push(new Object({issue:"real crime", name: "Real Crime Edition", id:"real-crime-001", title:"real-crime-001:Erhängt", hint:"In einem leeren Raum hing ein Mann an einem Strick, unter ihm war eine Wasserlache.", solution:""}));
bss.push(new Object({issue:"real crime", name: "Real Crime Edition", id:"real-crime-002", title:"real-crime-002:Erhängt", hint:"In einem leeren Raum hing ein Mann an einem Strick, unter ihm war eine Wasserlache.", solution:""}));
bss.push(new Object({issue:"real crime", name: "Real Crime Edition", id:"real-crime-003", title:"real-crime-003:Erhängt", hint:"In einem leeren Raum hing ein Mann an einem Strick, unter ihm war eine Wasserlache.", solution:""}));

bss.push(new Object({issue:"shit happens", name: "Shit Happens Edition", id:"shit-happens-001", title:"real-crime-001:Erhängt", hint:"In einem leeren Raum hing ein Mann an einem Strick, unter ihm war eine Wasserlache.", solution:""}));
bss.push(new Object({issue:"shit happens", name: "Shit Happens Edition", id:"shit-happens-002", title:"real-crime-002:Erhängt", hint:"In einem leeren Raum hing ein Mann an einem Strick, unter ihm war eine Wasserlache.", solution:""}));
bss.push(new Object({issue:"shit happens", name: "Shit Happens Edition", id:"shit-happens-003", title:"real-crime-003:Erhängt", hint:"In einem leeren Raum hing ein Mann an einem Strick, unter ihm war eine Wasserlache.", solution:""}));

bss.push(new Object({issue:"calendar 2015", name: "Calendar 2015", id:"calendar-2015-001", title:"calendar-2015-001: Erhängt", hint:"In einem leeren Raum hing ein Mann an einem Strick, unter ihm war eine Wasserlache.", solution:""}));
bss.push(new Object({issue:"calendar 2015", name: "Calendar 2015", id:"calendar-2015-002", title:"calendar-2015-002: Erhängt", hint:"In einem leeren Raum hing ein Mann an einem Strick, unter ihm war eine Wasserlache.", solution:""}));
bss.push(new Object({issue:"calendar 2015", name: "Calendar 2015", id:"calendar-2015-003", title:"calendar-2015-003: Erhängt", hint:"In einem leeren Raum hing ein Mann an einem Strick, unter ihm war eine Wasserlache.", solution:""}));
